# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-06 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='downvotes',
            new_name='likes',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='upvotes',
        ),
    ]
